### ISSUE TITLE
Incohérence / erreur dans le tutroriel

### ISSUE THREAD

**Issue by DoomDuck** [tolokoban/webgl-experiments#1]
Bonjour, j'ai trouvé une incohérence dans votre tutoriel.
Dans :
Introduction aux concepts fondamentaux

Juste après le passage suivant : "Il faut maintenant décrire ce qu'on a mis dans l'ARRAY_BUFFER."
vers la fin du document. Le code présenté n'est pas le bon. Au lieu de nous expliquer comment décrire nos donnés au WebGL, il y est répéter comment liée compiler et créer nos shaders.

J'ai pu me débrouiller en regardant le code source du résultat donné en lien.
Mais je n'ai pas pu identifier l'origine du "bug".

Merci pour cette excellent tutoriel. 💯

**Comment by tolokoban** [comment]
Merci pour cette remarque perspicace.
J'ai corrigé et mis en ligne. Un copier/coller malencontreux...
